name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test IO Core
      run: make test
    - name: clean
      run: make clean
    - name: Test IO Core in debug mode
      run: make test/db
